/** All non-medical tuning choices for the deterministic Cycle Engine v2. */
export const CYCLE_MODEL_V2_CONFIG = {
  version: "cycle-engine-v2.0",
  recencyHalfLifeCycles: 4,
  madScale: 1.4826,
  computationScaleFloorDays: 1,
  observationNoiseFloorDays: 1.5,
  huberLimit: 2.5,
  outlierScaleMultiplier: 3,
  outlierMinimumDays: 7,
  extremeIntervalMinimumDays: 15,
  extremeIntervalMaximumDays: 90,
  missingGapMultiplier: 1.6,
  missingGapRelativeTolerance: 0.15,
  missingGapMinimumToleranceDays: 2,
  missingGapMultiples: [2, 3, 4] as const,
  trendDamping: 0.8,
  initialLevelStandardDeviationDays: 8,
  initialTrendStandardDeviationDays: 1,
  minimumLevelProcessNoiseDays: 0.35,
  levelProcessNoiseScale: 0.15,
  minimumTrendProcessNoiseDays: 0.1,
  trendProcessNoiseScale: 0.05,
  dynamicBlendStartEffectiveSamples: 2,
  dynamicBlendRampEffectiveSamples: 6,
  dynamicBlendMaximum: 0.75,
  sparseUncertaintyNumeratorDays: 8,
  predictiveStandardDeviationFloorDays: 1.5,
  tailVarianceWeight: 0.25,
  outlierVarianceInflation: 0.5,
  missingVarianceInflation: 0.75,
  shockVarianceInflation: 0.75,
  studentTDegreesOfFreedomBase: 3,
  studentTDegreesOfFreedomMaximum: 30,
  distributionTailMass: 1e-8,
  distributionMaximumCycleDays: 730,
  predictionWindowCoverage: 0.8 as const,
  calibrationMinimumPredictions: 5,
  calibrationRecentPredictions: 12,
  calibrationMinimumFactor: 0.75,
  calibrationMaximumFactor: 2.5,
  confidence: {
    lowEffectiveSamples: 2.5,
    highEffectiveSamples: 6,
    highBacktests: 6,
    highMedianAbsoluteErrorDays: 2,
    highMinimumCoverage: 0.67,
    highMaximumWindowDays: 10,
    highMaximumVariabilityRatio: 0.12,
    moderateBacktests: 2,
    moderateMedianAbsoluteErrorDays: 4,
    moderateMinimumCoverage: 0.5,
    moderateMaximumWindowDays: 16,
    moderateMaximumVariabilityRatio: 0.2,
    lowMaximumWindowDays: 20,
  },
} as const;
