import type { AuthenticationService } from "../auth/contracts";
import { AuthError } from "../auth/errors";
import type { AuthSessionState } from "../auth/session";
import type { AppRoute, RoutePath } from "../app/routes";
import { queryFromHash } from "../app/router";
import { bindCalendarPage, renderCalendarPage } from "../calendar/calendarPage";
import type { CoupleApplicationService } from "../couple/contracts";
import type { CoupleSessionState } from "../couple/session";
import type { CoupleMembership, InviteDetails, Presence } from "../couple/types";
import { predictCycle, type Period } from "../cycle";
import type { CoupleEvent, CoupleEventKind } from "../events/types";
import type { CoupleEventService } from "../events/service";
import { askForNotificationPermission, notificationState } from "../notifications/localNotifications";
import { enableFirebasePush } from "../notifications/firebasePush";
import type { OfflinePeriodService } from "../sync/offlinePeriodService";
import type { SyncOperation, SyncState } from "../sync/types";
import { calendarDate, formatCalendarDate, type CalendarDate } from "../utils/date";

interface RenderContext {
  auth: AuthenticationService; couples: CoupleApplicationService; authSession: AuthSessionState; coupleSession: CoupleSessionState;
  invite: InviteDetails | undefined; inviteLoading?: boolean; firebaseConfigured: boolean; navigate: (path: string) => void;
  setMembership: (membership: CoupleMembership, invite?: InviteDetails) => void; setInvite?: (invite: InviteDetails) => void;
  periods: readonly Period[]; periodsLoading: boolean; periodsError: boolean; periodService: OfflinePeriodService; refreshPeriods: () => Promise<void>;
  syncState: SyncState; syncOperations: readonly SyncOperation[]; presence: readonly Presence[]; events: readonly CoupleEvent[]; eventService: CoupleEventService; rerender: () => void;
}

const href = (path: RoutePath) => `#${path}`;
let composerOpen = false;
const icon = (glyph: string) => `<span class="nav-icon" aria-hidden="true">${glyph}</span>`;
const today = (): CalendarDate => { const d = new Date(); return calendarDate(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`); };
const userId = (context: RenderContext) => context.authSession.status === "authenticated" ? context.authSession.user.uid : "";
const escapeHtml = (value: string) => value.replace(/[&<>'"]/gu, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char);
const syncText = (state: SyncState) => ({ synced: "Đã đồng bộ", syncing: "Đang đồng bộ", offline: "Ngoại tuyến", pending: "Đang chờ đồng bộ", error: "Có lỗi đồng bộ" })[state];

function shell(content: string): string {
  return `<div class="app-shell"><header class="topbar"><a class="brand" data-route href="#/home"><span class="brand-mark">♡</span><span>Nhịp Đôi</span></a><span class="topbar-tag">Dành cho hai người</span></header>${content}<div id="pwa-notices" class="pwa-notices"></div></div>`;
}

export function renderApplication(root: HTMLElement, route: AppRoute, context: RenderContext): void {
  if (context.authSession.status === "initializing") { root.innerHTML = shell(loading("Đang mở không gian riêng tư")); return; }
  if (["/login", "/register", "/forgot-password"].includes(route.path)) { renderAuth(root, route.path, context); return; }
  if (context.coupleSession.status === "initializing") { root.innerHTML = shell(loading("Đang kết nối hai bạn")); return; }
  if (context.coupleSession.status !== "linked") { renderOnboarding(root, context); return; }
  const membership = context.coupleSession.membership;
  if (route.path === "/invite") { renderInvite(root, context); return; }
  const page = route.path === "/home" ? home(context, membership) : route.path === "/calendar" ? calendar(context, membership) : route.path === "/history" ? history(context) : route.path === "/insights" ? insights(context) : settings(context, membership);
  const menu: readonly [RoutePath, string, string][] = [["/home", "Hôm nay", "⌂"], ["/calendar", "Lịch", "□"], ["/history", "Nhật ký", "◫"], ["/insights", "Khám phá", "✦"], ["/settings", "Cá nhân", "◯"]];
  root.innerHTML = shell(`<main class="page app-page"><div class="connection-strip"><span class="sync-dot sync-${context.syncState}"></span>${syncText(context.syncState)}<span>Không gian riêng tư</span></div>${page}</main><nav class="bottom-nav">${menu.map(([path, label, glyph]) => `<a data-route href="${href(path)}" ${route.path === path ? 'aria-current="page"' : ""}>${icon(glyph)}<small>${label}</small></a>`).join("")}</nav>${composerOpen ? eventForm() : ""}`);
  if (route.path === "/calendar") bindCalendarPage(root, { periods: context.periods, loading: context.periodsLoading, error: context.periodsError, coupleId: membership.coupleId, uid: userId(context), service: context.periodService, refresh: context.refreshPeriods, rerender: context.rerender });
  bindCommon(root, context, membership);
}

function loading(title: string): string { return `<main class="auth-layout"><section class="auth-card auth-loading"><span class="loading-indicator"></span><h1>${title}</h1><p>Chỉ một chút thôi nhé…</p></section></main>`; }
function renderAuth(root: HTMLElement, path: RoutePath, context: RenderContext): void {
  const title = path === "/login" ? "Chào mừng bạn trở lại" : path === "/register" ? "Tạo không gian của hai bạn" : "Đặt lại mật khẩu";
  const form = path === "/login" ? login() : path === "/register" ? register() : reset();
  root.innerHTML = shell(`<main class="auth-layout"><section class="auth-intro"><span class="hero-orb">♡</span><p class="eyebrow">KHÔNG GIAN RIÊNG TƯ CHO HAI NGƯỜI</p><h1>${title}</h1><p class="description">Cùng ghi nhớ những điều quan trọng và quan tâm nhau đúng lúc.</p></section><section class="auth-card">${!context.firebaseConfigured ? '<p class="configuration-note">Ứng dụng chưa được kết nối máy chủ nên chưa thể đăng nhập.</p>' : ""}${form}</section></main>`);
  root.querySelector<HTMLFormElement>("#auth-form")?.addEventListener("submit", (event) => { event.preventDefault(); const formElement = event.currentTarget as HTMLFormElement; const data = new FormData(formElement); const value = (key: string) => String(data.get(key) ?? ""); const action = path === "/login" ? context.auth.login({ email: value("email"), password: value("password") }) : path === "/register" ? context.auth.register({ displayName: value("displayName"), email: value("email"), password: value("password"), passwordConfirmation: value("passwordConfirmation") }) : context.auth.requestPasswordReset(value("email")); void action.then(() => { if (path === "/forgot-password") setFormStatus(formElement, "Nếu email này có tài khoản, liên kết đặt lại đã được gửi."); else context.navigate("/onboarding"); }).catch((error: unknown) => setFormStatus(formElement, error instanceof AuthError ? error.message : "Đã có lỗi xảy ra. Vui lòng thử lại.")); });
}
function field(id: string, label: string, type: string, placeholder: string): string { return `<label class="field">${label}<input id="${id}" name="${id}" type="${type}" placeholder="${placeholder}" required><small></small></label>`; }
function submit(label: string): string { return `<p class="form-status"></p><button class="primary-button" type="submit">${label} <b>→</b></button>`; }
function login(): string { return `<form id="auth-form">${field("email", "Email", "email", "ban@example.com")}${field("password", "Mật khẩu", "password", "••••••••")}<p class="form-row"><a data-route href="#/forgot-password">Quên mật khẩu?</a></p>${submit("Đăng nhập")}<p class="auth-switch">Chưa có tài khoản? <a data-route href="#/register">Tạo tài khoản</a></p></form>`; }
function register(): string { return `<form id="auth-form">${field("displayName", "Tên của bạn", "text", "Ví dụ: Minh")}${field("email", "Email", "email", "ban@example.com")}${field("password", "Mật khẩu", "password", "Tối thiểu 8 ký tự")}${field("passwordConfirmation", "Nhập lại mật khẩu", "password", "••••••••")}${submit("Tạo tài khoản")}<p class="auth-switch">Đã có tài khoản? <a data-route href="#/login">Đăng nhập</a></p></form>`; }
function reset(): string { return `<form id="auth-form">${field("email", "Email", "email", "ban@example.com")}${submit("Gửi liên kết đặt lại")}<p class="auth-switch"><a data-route href="#/login">Quay lại đăng nhập</a></p></form>`; }
function setFormStatus(form: HTMLFormElement, text: string): void { const target = form.querySelector<HTMLElement>(".form-status"); if (target) target.textContent = text; }

function home(context: RenderContext, membership: CoupleMembership): string {
  const prediction = predictCycle({ periods: context.periods, asOfDate: today() });
  const events = context.events.filter((event) => event.date >= today()).slice(0, 3);
  const cycle = prediction.expectedDate ? `Dự kiến ${formatCalendarDate(prediction.expectedDate)}` : "Ghi thêm chu kỳ để có dự đoán riêng";
  return `<section class="today-page"><div class="welcome-row"><div><p class="eyebrow">HÔM NAY</p><h1>${escapeHtml(membership.profile.name)}</h1><p>Nhẹ nhàng để ý nhau một chút nhé.</p></div><button class="round-button" data-open-event type="button">＋</button></div><section class="hero-card"><span>♡ NHỊP CỦA HAI BẠN</span><h2>${cycle}</h2><p>${prediction.expectedDate ? "Dự đoán từ những lần bạn đã ghi nhận." : "Mỗi lần ghi nhận giúp ứng dụng hiểu bạn hơn."}</p><a data-route href="#/calendar">Mở lịch chu kỳ →</a></section><section class="checkin-card"><div><p class="eyebrow">CHECK-IN 10 GIÂY</p><h2>Hôm nay bạn thấy thế nào?</h2></div><div class="mood-row">${[["😊", "vui"], ["😌", "ổn"], ["😔", "mệt"], ["🥺", "cần ôm"]].map(([emoji, label]) => `<button data-mood="${label}" type="button"><b>${emoji}</b><small>${label}</small></button>`).join("")}</div></section><section class="section-heading"><div><p class="eyebrow">SẮP TỚI</p><h2>Ngày của hai bạn</h2></div><button data-open-event class="text-button" type="button">Thêm mới</button></section>${events.length ? `<div class="event-list">${events.map(eventCard).join("")}</div>` : `<section class="empty-events"><span>♡</span><strong>Chưa có ngày quan trọng</strong><p>Thêm ngày yêu nhau, sinh nhật hoặc buổi hẹn để được nhắc đúng lúc.</p><button data-open-event class="secondary-button" type="button">Thêm ngày</button></section>`}<section class="gentle-tip"><span>✦</span><p><strong>Một gợi ý nhỏ</strong><br>Gửi người ấy một lời hỏi thăm ngắn — đôi khi vậy là đủ để ngày hôm nay ấm áp hơn.</p></section></section>`;
}
function eventCard(event: CoupleEvent): string { const kinds: Record<CoupleEventKind, string> = { anniversary: "Kỷ niệm", birthday: "Sinh nhật", holiday: "Ngày lễ", date: "Hẹn hò", custom: "Ngày quan trọng" }; return `<article class="event-card"><span class="event-date"><b>${Number(event.date.slice(8))}</b><small>THG ${Number(event.date.slice(5, 7))}</small></span><div><small>${kinds[event.kind]}</small><h3>${escapeHtml(event.title)}</h3><p>${event.reminderDays.length ? `Nhắc trước ${event.reminderDays.join(", ")} ngày` : "Chưa bật lời nhắc"}</p></div><button data-remove-event="${event.id}" type="button" aria-label="Xóa">×</button></article>`; }
function calendar(context: RenderContext, membership: CoupleMembership): string { return renderCalendarPage({ periods: context.periods, loading: context.periodsLoading, error: context.periodsError, coupleId: membership.coupleId, uid: userId(context), service: context.periodService, refresh: context.refreshPeriods, rerender: context.rerender }); }
function history(context: RenderContext): string { return `<section class="content-page"><p class="eyebrow">NHẬT KÝ RIÊNG</p><h1>Những điều đã ghi</h1><p class="page-lead">Nhìn lại nhịp sinh hoạt của bạn theo cách dịu dàng và riêng tư.</p><section class="history-card"><h2>Chu kỳ đã ghi nhận</h2>${context.periods.length ? `<ol class="history-list">${context.periods.map((period) => `<li><b>${formatCalendarDate(period.startDate)}${period.endDate ? ` — ${formatCalendarDate(period.endDate)}` : ""}</b><small>Thông tin riêng tư của hai bạn</small></li>`).join("")}</ol>` : "<p>Chưa có dữ liệu. Bắt đầu bằng việc ghi nhận kỳ gần nhất của bạn.</p>"}</section></section>`; }
function insights(context: RenderContext): string { const prediction = predictCycle({ periods: context.periods, asOfDate: today() }); return `<section class="content-page"><p class="eyebrow">HIỂU HƠN MỖI NGÀY</p><h1>Nhịp của bạn</h1><p class="page-lead">Một vài điểm chạm nhẹ nhàng, không thay thế tư vấn y tế.</p><section class="insight-feature"><span>✦</span><small>DỰ ĐOÁN KỲ TIẾP THEO</small><h2>${prediction.expectedDate ? formatCalendarDate(prediction.expectedDate) : "Chưa đủ dữ liệu"}</h2><p>Ghi nhận đều đặn giúp dự đoán ngày càng phù hợp hơn.</p></section><div class="insight-grid"><section><small>Chu kỳ điển hình</small><strong>${prediction.cycleLength.expected ? `${prediction.cycleLength.expected} ngày` : "—"}</strong></section><section><small>Lần ghi nhận</small><strong>${context.periods.length}</strong></section></div></section>`; }
function settings(context: RenderContext, membership: CoupleMembership): string { const state = notificationState(); return `<section class="content-page"><p class="eyebrow">KHÔNG GIAN CỦA BẠN</p><h1>Cá nhân & riêng tư</h1><section class="settings-card"><span>${membership.profile.name.slice(0, 1)}</span><div><strong>${escapeHtml(membership.profile.name)}</strong><p>Không gian chỉ dành cho hai bạn</p></div></section><section class="settings-group"><h2>Thông báo</h2><button id="notification-button" class="settings-row" type="button"><span>♧</span><div><strong>Nhắc ngày quan trọng</strong><small>${state === "granted" ? "Đã bật trên thiết bị này" : "Bật để nhận lời nhắc đúng lúc"}</small></div><b>${state === "granted" ? "Đã bật" : "Bật"}</b></button><p id="notification-status" class="form-status"></p></section><section class="settings-group"><h2>Dữ liệu</h2><div class="settings-row"><span>♡</span><div><strong>Quyền riêng tư</strong><small>Dữ liệu chỉ hiển thị trong không gian chung.</small></div></div><div class="settings-row"><span>↻</span><div><strong>Đồng bộ</strong><small>${syncText(context.syncState)}</small></div></div></section><button id="logout-button" class="secondary-button logout-button" type="button">Đăng xuất</button></section>`; }
function eventForm(): string { return `<div id="sheet-backdrop" class="sheet-backdrop"><section class="event-sheet"><button id="close-sheet" class="sheet-close" type="button">×</button><span class="sheet-pill"></span><p class="eyebrow">NGÀY CỦA HAI BẠN</p><h2>Thêm một điều đáng nhớ</h2><form id="event-form">${field("event-title", "Tên sự kiện", "text", "Ví dụ: Kỷ niệm yêu nhau")}<div class="event-form-grid"><label class="field">Ngày diễn ra<input id="event-date" name="event-date" type="date" value="${today()}" required></label><label class="field">Loại ngày<select name="kind"><option value="anniversary">Kỷ niệm</option><option value="birthday">Sinh nhật</option><option value="date">Hẹn hò</option><option value="holiday">Ngày lễ</option><option value="custom">Tùy chỉnh</option></select></label></div><fieldset><legend>Nhắc trước</legend><label><input type="checkbox" name="reminder" value="7" checked> 7 ngày</label><label><input type="checkbox" name="reminder" value="3" checked> 3 ngày</label><label><input type="checkbox" name="reminder" value="1" checked> 1 ngày</label><label><input type="checkbox" name="reminder" value="0"> Đúng ngày</label></fieldset><p class="form-status"></p><button class="primary-button" type="submit">Lưu ngày quan trọng →</button></form></section></div>`; }

function bindCommon(root: HTMLElement, context: RenderContext, membership: CoupleMembership): void {
  root.querySelectorAll<HTMLButtonElement>("[data-open-event]").forEach((button) => button.addEventListener("click", () => { composerOpen = true; context.rerender(); }));
  root.querySelector<HTMLButtonElement>("#close-sheet")?.addEventListener("click", () => { composerOpen = false; context.rerender(); });
  root.querySelector<HTMLButtonElement>("#logout-button")?.addEventListener("click", () => { void context.auth.logout().then(() => context.navigate("/login")); });
  root.querySelector<HTMLButtonElement>("#notification-button")?.addEventListener("click", () => { void askForNotificationPermission().then(async (permission) => { if (permission !== "granted") { context.rerender(); return; } if (!context.firebaseConfigured) { setText(root, "#notification-status", "Đã bật nhắc khi ứng dụng đang mở. Kết nối Firebase để nhận push khi app đóng."); return; } const result = await enableFirebasePush(membership.coupleId, userId(context)); if (result === "missing-vapid") setText(root, "#notification-status", "Thiếu VAPID key. Hãy thêm VITE_FIREBASE_VAPID_KEY vào cấu hình."); else if (result === "unsupported") setText(root, "#notification-status", "Trình duyệt này chưa hỗ trợ thông báo đẩy."); else context.rerender(); }).catch(() => setText(root, "#notification-status", "Không thể bật thông báo trên thiết bị này.")); });
  root.querySelectorAll<HTMLButtonElement>("[data-mood]").forEach((button) => button.addEventListener("click", () => { try { localStorage.setItem(`nhip-doi:checkin:${today()}`, button.dataset.mood ?? "ổn"); } catch { /* optional */ } button.classList.add("active"); }));
  root.querySelectorAll<HTMLButtonElement>("[data-remove-event]").forEach((button) => button.addEventListener("click", () => { if (!window.confirm("Xóa ngày quan trọng này?")) return; void context.eventService.remove(membership.coupleId, button.dataset.removeEvent ?? "").catch(() => undefined); }));
  root.querySelector<HTMLFormElement>("#event-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const data = new FormData(form); let date: CalendarDate; try { date = calendarDate(String(data.get("event-date"))); } catch { setFormStatus(form, "Hãy chọn ngày hợp lệ."); return; } void context.eventService.create(membership.coupleId, userId(context), { title: String(data.get("event-title") ?? ""), date, kind: String(data.get("kind")) as CoupleEventKind, reminderDays: data.getAll("reminder").map(Number) }).then(() => { composerOpen = false; context.rerender(); }).catch((error: unknown) => setFormStatus(form, error instanceof Error ? error.message : "Không thể lưu sự kiện.")); });
}
function renderOnboarding(root: HTMLElement, context: RenderContext): void {
  const query = queryFromHash(window.location.hash);
  root.innerHTML = shell(`<main class="page onboarding-page"><p class="eyebrow">BẮT ĐẦU CÙNG NHAU</p><h1>Tạo không gian của hai bạn</h1><p class="page-lead">Mỗi không gian chỉ dành cho đúng hai người.</p><section class="auth-card flow-card"><h2>Tạo không gian</h2><form id="couple-form">${field("name", "Tên không gian", "text", "Ví dụ: Minh & An")}${submit("Tạo và mời người ấy")}</form></section></main>`);
  root.querySelector<HTMLFormElement>("#couple-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; void context.couples.createCouple(userId(context), String(new FormData(form).get("name") ?? "")).then((result) => { context.setMembership(result.membership, result.invite); context.navigate("/invite"); }).catch((error: unknown) => setFormStatus(form, error instanceof Error ? error.message : "Không thể tạo không gian.")); });
  if (query.get("couple")) void query;
}
function setText(root: HTMLElement, selector: string, message: string): void { const target = root.querySelector<HTMLElement>(selector); if (target) target.textContent = message; }
function renderInvite(root: HTMLElement, context: RenderContext): void {
  const invite = context.invite;
  const url = invite ? `${window.location.origin}${window.location.pathname}#/onboarding?couple=${encodeURIComponent(invite.coupleId)}&invite=${encodeURIComponent(invite.code)}` : "";
  root.innerHTML = shell(`<main class="page"><section class="notice-card invite-card"><span class="hero-orb">♡</span><p class="eyebrow">MỜI NGƯỜI ẤY</p><h1>Chia sẻ không gian này</h1><p>Gửi liên kết riêng tư bên dưới cho người bạn muốn đồng hành.</p>${invite ? `<div class="share-row"><input id="invite-link" readonly value="${escapeHtml(url)}"><button id="copy-invite" class="secondary-button" type="button">Sao chép</button></div>` : "<p>Đang tạo lời mời…</p>"}<a class="primary-link" data-route href="#/home">Đến trang hôm nay →</a></section></main>`);
  root.querySelector<HTMLButtonElement>("#copy-invite")?.addEventListener("click", () => { void navigator.clipboard.writeText(url); });
}
