import type { AuthenticationService } from "../auth/contracts";
import { AuthError } from "../auth/errors";
import type { AuthSessionState } from "../auth/session";
import type { AppRoute, RoutePath } from "../app/routes";
import { queryFromHash } from "../app/router";
import { bindCalendarPage, renderCalendarPage } from "../calendar/calendarPage";
import type { CoupleApplicationService } from "../couple/contracts";
import type { CoupleSessionState } from "../couple/session";
import type { CoupleMembership, InviteDetails, Presence } from "../couple/types";
import { predictCycle, type Period } from "../cycle";
import type { CoupleEvent, CoupleEventKind } from "../events/types";
import type { CoupleEventService } from "../events/service";
import { suggestedHolidays } from "../events/vietnamHolidays";
import type { DailyConnectionService } from "../daily/service";
import type { Mood, PrivateCheckIn, SharedTask } from "../daily/types";
import { askForNotificationPermission, notificationState } from "../notifications/localNotifications";
import { enableFirebasePush } from "../notifications/firebasePush";
import type { OfflinePeriodService } from "../sync/offlinePeriodService";
import type { SyncOperation, SyncState } from "../sync/types";
import { calendarDate, formatCalendarDate, type CalendarDate } from "../utils/date";
import { loveDayCount, loveDateFromInput, nextLoveMilestone } from "../couple/loveDay";
import { dailyCoupleMessage } from "../daily/messages";
import type { CoupleFeatureService } from "../couple/features";
import { applyTheme, currentTheme, type ThemeName } from "../settings/theme";
import { uploadAvatar } from "../storage/avatar";

interface RenderContext {
  auth: AuthenticationService; couples: CoupleApplicationService; authSession: AuthSessionState; coupleSession: CoupleSessionState;
  invite: InviteDetails | undefined; inviteLoading?: boolean; firebaseConfigured: boolean; navigate: (path: string) => void;
  setMembership: (membership: CoupleMembership, invite?: InviteDetails) => void; setInvite?: (invite: InviteDetails) => void; updateStartDate: (startDate: string) => Promise<void>;
  periods: readonly Period[]; periodsLoading: boolean; periodsError: boolean; periodService: OfflinePeriodService; refreshPeriods: () => Promise<void>;
  syncState: SyncState; syncOperations: readonly SyncOperation[]; presence: readonly Presence[]; events: readonly CoupleEvent[]; eventService: CoupleEventService;
  sharedTasks: readonly SharedTask[]; privateCheckins: readonly PrivateCheckIn[]; dailyService: DailyConnectionService; rerender: () => void;
  featureService: CoupleFeatureService;
}

const href = (path: RoutePath) => `#${path}`;
let composerOpen = false;
const icon = (name: string) => `<span class="nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><use href="#icon-${name}"></use></svg></span>`;
const today = (): CalendarDate => { const d = new Date(); return calendarDate(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`); };
const userId = (context: RenderContext) => context.authSession.status === "authenticated" ? context.authSession.user.uid : "";
const escapeHtml = (value: string) => value.replace(/[&<>'"]/gu, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char);
const syncText = (state: SyncState) => ({ synced: "Đã đồng bộ", syncing: "Đang đồng bộ", offline: "Ngoại tuyến", pending: "Đang chờ đồng bộ", error: "Có lỗi đồng bộ" })[state];

function shell(content: string): string {
  return `<div class="app-shell"><svg class="icon-sprite" aria-hidden="true"><symbol id="icon-home" viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1Z"/></symbol><symbol id="icon-calendar" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></symbol><symbol id="icon-couple" viewBox="0 0 24 24"><circle cx="8" cy="8" r="3"/><circle cx="16" cy="8" r="3"/><path d="M3 20c.4-4 2.2-6 5-6s4.6 2 5 6M11 20c.4-4 2.2-6 5-6s4.6 2 5 6"/></symbol><symbol id="icon-heart" viewBox="0 0 24 24"><path d="M20.8 8.8c0 5.3-8.8 10.2-8.8 10.2S3.2 14.1 3.2 8.8A4.8 4.8 0 0 1 12 6.1a4.8 4.8 0 0 1 8.8 2.7Z"/></symbol><symbol id="icon-insights" viewBox="0 0 24 24"><path d="M4 19V5M4 19h17M8 15l3-4 3 2 5-7"/></symbol><symbol id="icon-profile" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.7-4 3.3-6 8-6s7.3 2 8 6"/></symbol><symbol id="icon-plus" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></symbol><symbol id="icon-link" viewBox="0 0 24 24"><path d="M9 15 7 17a3 3 0 0 1-4-4l3-3a3 3 0 0 1 4 0M15 9l2-2a3 3 0 0 1 4 4l-3 3a3 3 0 0 1-4 0M8 16l8-8"/></symbol></svg><header class="topbar"><a class="brand" data-route href="#/home"><span class="brand-mark"><svg viewBox="0 0 24 24"><use href="#icon-heart"></use></svg></span><span>Nhịp Đôi</span></a></header>${content}<div id="pwa-notices" class="pwa-notices"></div></div>`;
}

export function renderApplication(root: HTMLElement, route: AppRoute, context: RenderContext): void {
  if (context.authSession.status === "initializing") { root.innerHTML = shell(loading("Đang mở không gian riêng tư")); return; }
  if (["/login", "/register", "/forgot-password"].includes(route.path)) { renderAuth(root, route.path, context); return; }
  if (context.coupleSession.status === "initializing") { root.innerHTML = shell(loading("Đang kết nối hai bạn")); return; }
  if (context.coupleSession.status !== "linked") { renderOnboarding(root, context); return; }
  const membership = context.coupleSession.membership;
  if (route.path === "/invite") { renderInvite(root, context); return; }
  const page = route.path === "/home" ? home(context, membership) : route.path === "/calendar" ? calendar(context, membership) : route.path === "/history" ? history(context, membership) : route.path === "/insights" ? insights(context) : settings(context, membership);
  const menu: readonly [RoutePath, string, string][] = [["/home", "Hôm nay", "home"], ["/calendar", "Lịch", "calendar"], ["/history", "Chúng mình", "couple"], ["/insights", "Thống kê", "insights"], ["/settings", "Cá nhân", "profile"]];
  root.innerHTML = shell(`<main class="page app-page"><div class="connection-strip"><span class="sync-dot sync-${context.syncState}"></span>${syncText(context.syncState)}</div>${page}</main><nav class="bottom-nav">${menu.map(([path, label, glyph]) => `<a data-route href="${href(path)}" ${route.path === path ? 'aria-current="page"' : ""}>${icon(glyph)}<small>${label}</small></a>`).join("")}</nav>${composerOpen ? eventForm() : ""}`);
  if (route.path === "/calendar") bindCalendarPage(root, { periods: context.periods, loading: context.periodsLoading, error: context.periodsError, coupleId: membership.coupleId, uid: userId(context), service: context.periodService, refresh: context.refreshPeriods, rerender: context.rerender });
  bindCommon(root, context, membership);
}

function loading(title: string): string { return `<main class="auth-layout"><section class="auth-card auth-loading"><span class="loading-indicator"></span><h1>${title}</h1><p>Chỉ một chút thôi nhé…</p></section></main>`; }
function renderAuth(root: HTMLElement, path: RoutePath, context: RenderContext): void {
  const title = path === "/login" ? "Chào mừng bạn trở lại" : path === "/register" ? "Tạo không gian của hai bạn" : "Đặt lại mật khẩu";
  const form = path === "/login" ? login() : path === "/register" ? register() : reset();
  root.innerHTML = shell(`<main class="auth-layout"><section class="auth-intro"><span class="hero-orb">♡</span><p class="eyebrow">KHÔNG GIAN RIÊNG TƯ CHO HAI NGƯỜI</p><h1>${title}</h1><p class="description">Cùng ghi nhớ những điều quan trọng và quan tâm nhau đúng lúc.</p></section><section class="auth-card">${!context.firebaseConfigured ? '<p class="configuration-note">Ứng dụng chưa được kết nối máy chủ nên chưa thể đăng nhập.</p>' : ""}${form}</section></main>`);
  root.querySelector<HTMLFormElement>("#auth-form")?.addEventListener("submit", (event) => { event.preventDefault(); const formElement = event.currentTarget as HTMLFormElement; const data = new FormData(formElement); const value = (key: string) => String(data.get(key) ?? ""); const action = path === "/login" ? context.auth.login({ email: value("email"), password: value("password") }) : path === "/register" ? context.auth.register({ displayName: value("displayName"), email: value("email"), password: value("password"), passwordConfirmation: value("passwordConfirmation") }) : context.auth.requestPasswordReset(value("email")); void action.then(() => { if (path === "/forgot-password") setFormStatus(formElement, "Nếu email này có tài khoản, liên kết đặt lại đã được gửi."); else context.navigate("/onboarding"); }).catch((error: unknown) => setFormStatus(formElement, error instanceof AuthError ? error.message : "Đã có lỗi xảy ra. Vui lòng thử lại.")); });
}
function field(id: string, label: string, type: string, placeholder: string): string { return `<label class="field">${label}<input id="${id}" name="${id}" type="${type}" placeholder="${placeholder}" required><small></small></label>`; }
function submit(label: string): string { return `<p class="form-status"></p><button class="primary-button" type="submit">${label}</button>`; }
function login(): string { return `<form id="auth-form">${field("email", "Email", "email", "ban@example.com")}${field("password", "Mật khẩu", "password", "••••••••")}<p class="form-row"><a data-route href="#/forgot-password">Quên mật khẩu?</a></p>${submit("Đăng nhập")}<p class="auth-switch">Chưa có tài khoản? <a data-route href="#/register">Tạo tài khoản</a></p></form>`; }
function register(): string { return `<form id="auth-form">${field("displayName", "Tên của bạn", "text", "Ví dụ: Minh")}${field("email", "Email", "email", "ban@example.com")}${field("password", "Mật khẩu", "password", "Tối thiểu 8 ký tự")}${field("passwordConfirmation", "Nhập lại mật khẩu", "password", "••••••••")}${submit("Tạo tài khoản")}<p class="auth-switch">Đã có tài khoản? <a data-route href="#/login">Đăng nhập</a></p></form>`; }
function reset(): string { return `<form id="auth-form">${field("email", "Email", "email", "ban@example.com")}${submit("Gửi liên kết đặt lại")}<p class="auth-switch"><a data-route href="#/login">Quay lại đăng nhập</a></p></form>`; }
function setFormStatus(form: HTMLFormElement, text: string): void { const target = form.querySelector<HTMLElement>(".form-status"); if (target) target.textContent = text; }

function loveDateForm(value: string, buttonLabel: string): string {
  return `<form id="love-date-form" class="love-date-form" novalidate><label for="love-date">Ngày bắt đầu của hai bạn<input id="love-date" name="love-date" type="date" value="${escapeHtml(value)}" max="${today()}" required></label><button class="primary-button" type="submit">${buttonLabel}</button><p class="form-status" role="alert"></p></form>`;
}

function home(context: RenderContext, membership: CoupleMembership): string {
  const events = context.events.filter((event) => event.date >= today()).slice(0, 3);
  const ownCheckin = context.privateCheckins.find((checkin) => checkin.date === today());
  const tasks = context.sharedTasks.slice(0, 4);
  const startDate = membership.profile.startDate;
  const parsedStartDate = startDate ? loveDateFromInput(startDate) : null;
  const dayCount = parsedStartDate ? loveDayCount(parsedStartDate, today()) : 0;
  const milestone = dayCount ? nextLoveMilestone(dayCount) : 0;
  const moodOptions: readonly [string, Mood, string][] = [["😊", "vui", "Vui"], ["😌", "on", "Ổn"], ["😮‍💨", "met", "Mệt"], ["🥺", "can-om", "Cần ôm"]];
  const initials = membership.profile.name.trim().slice(0, 1).toUpperCase() || "♡";
  const counter = parsedStartDate ? `<div class="avatar-pair"><span>${escapeHtml(initials)}</span><i>${icon("heart")}</i><span class="partner-avatar">♡</span></div><div class="love-counter-row"><div><span class="counter-label">ĐÃ BÊN NHAU</span><strong class="love-count">${dayCount.toLocaleString("vi-VN")}</strong><span class="counter-unit">ngày</span></div><span class="counter-heart">${icon("heart")}</span></div><p class="love-subtitle">Từ ${formatCalendarDate(parsedStartDate)} · còn ${milestone - dayCount} ngày đến cột mốc ${milestone.toLocaleString("vi-VN")} ngày</p><div class="milestone-track" aria-label="Tiến độ đến cột mốc tiếp theo"><span style="width:${Math.min(100, Math.max(5, Math.round((dayCount / milestone) * 100)))}%"></span></div><div class="milestone-caption"><span>Cột mốc tiếp theo</span><b>${milestone.toLocaleString("vi-VN")} ngày</b></div><div class="hero-actions"><a class="secondary-button" data-route href="#/history">Xem hành trình</a><button class="ghost-button" type="button" data-copy-love>Chia sẻ</button></div><details class="love-date-details"><summary>Đổi ngày bắt đầu</summary>${loveDateForm(parsedStartDate, "Cập nhật ngày")}</details>` : `<div class="love-empty"><span class="empty-mark">${icon("heart")}</span><h2>Đếm từng ngày bên nhau</h2><p>Chọn ngày bắt đầu để Nhịp Đôi tự đếm số ngày yêu, và nhắc bạn về những cột mốc sắp tới.</p>${loveDateForm(today(), "Bắt đầu đếm ngày")}</div>`;
  return `<section class="today-page"><div class="welcome-row"><div><p class="eyebrow">HÔM NAY · ${formatCalendarDate(today())}</p><h1>Chào ${escapeHtml(membership.profile.name)}</h1><p>Chậm lại một nhịp để gần nhau hơn.</p></div><button class="round-button" data-open-event type="button" aria-label="Thêm ngày quan trọng">${icon("plus")}</button></div><section class="love-hero"><div class="hero-kicker">${icon("heart")}<span>ĐẾM NGÀY CỦA HAI BẠN</span></div>${counter}</section><section class="message-card"><div class="message-label">THÔNG ĐIỆP HÔM NAY</div><h2>${escapeHtml(dailyCoupleMessage(membership.coupleId, today(), dayCount || undefined))}</h2><div class="message-actions"><button type="button" data-copy-message>Gửi cho người ấy</button><button type="button" data-complete-message>Đã thực hiện</button></div></section><section class="checkin-card"><div><p class="eyebrow">CHECK-IN 10 GIÂY</p><h2>Hôm nay bạn thấy thế nào?</h2><small class="privacy-note">Riêng tư theo mặc định · bạn chọn khi muốn chia sẻ.</small></div><div class="mood-row">${moodOptions.map(([emoji, value, label]) => `<button data-mood="${value}" aria-label="${label}" class="${ownCheckin?.mood === value ? "active" : ""}" type="button"><b>${emoji}</b><small>${label}</small></button>`).join("")}</div></section><section class="shared-tasks"><div class="section-heading"><div><p class="eyebrow">CÙNG NHAU</p><h2>Việc nhỏ hôm nay</h2></div><span class="task-count">${context.sharedTasks.filter((task) => task.completed).length}/${context.sharedTasks.length}</span></div><form id="task-form" class="task-form"><input name="task-title" maxlength="120" placeholder="Ví dụ: Chọn phim cho tối nay" required><button type="submit" aria-label="Thêm việc">${icon("plus")}</button></form>${tasks.length ? `<ul class="task-list">${tasks.map((task) => `<li><button data-toggle-task="${task.id}" class="${task.completed ? "done" : ""}" type="button" aria-label="${task.completed ? "Đánh dấu chưa xong" : "Đánh dấu đã xong"}">${task.completed ? "✓" : ""}</button><span class="${task.completed ? "done" : ""}">${escapeHtml(task.title)}</span></li>`).join("")}</ul>` : `<p class="empty-task">Một việc bé xíu để cả hai cùng hoàn thành?</p>`}</section><section class="section-heading"><div><p class="eyebrow">SẮP TỚI</p><h2>Ngày của hai bạn</h2></div><button data-open-event class="text-button" type="button">Thêm mới</button></section>${events.length ? `<div class="event-list">${events.map(eventCard).join("")}</div>` : `<section class="empty-events"><span>${icon("calendar")}</span><strong>Chưa có ngày quan trọng</strong><p>Thêm ngày yêu nhau, sinh nhật hoặc buổi hẹn để được nhắc đúng lúc.</p><button data-open-event class="secondary-button" type="button">Thêm ngày</button></section>`}</section>`;
}
function eventCard(event: CoupleEvent): string { const kinds: Record<CoupleEventKind, string> = { anniversary: "Kỷ niệm", birthday: "Sinh nhật", holiday: "Ngày lễ", date: "Hẹn hò", custom: "Ngày quan trọng" }; return `<article class="event-card"><span class="event-date"><b>${Number(event.date.slice(8))}</b><small>THG ${Number(event.date.slice(5, 7))}</small></span><div><small>${kinds[event.kind]}</small><h3>${escapeHtml(event.title)}</h3><p>${event.reminderDays.length ? `Nhắc trước ${event.reminderDays.join(", ")} ngày` : "Chưa bật lời nhắc"}</p></div><button data-remove-event="${event.id}" type="button" aria-label="Xóa">Xóa</button></article>`; }
function calendar(context: RenderContext, membership: CoupleMembership): string { return renderCalendarPage({ periods: context.periods, loading: context.periodsLoading, error: context.periodsError, coupleId: membership.coupleId, uid: userId(context), service: context.periodService, refresh: context.refreshPeriods, rerender: context.rerender }); }
function history(context: RenderContext, membership: CoupleMembership): string { const features = context.featureService.list(membership.coupleId); return `<section class="content-page"><p class="eyebrow">KỶ NIỆM & HÀNH TRÌNH</p><h1>Chúng mình</h1><p class="page-lead">Những điều nhỏ được giữ lại để hai bạn có thể nhìn lại cùng nhau.</p><section class="history-card"><div class="section-heading"><h2>Dòng thời gian kỷ niệm</h2></div><form id="memory-form" class="memory-form"><input name="memory-title" required maxlength="80" placeholder="Tiêu đề kỷ niệm"><input name="memory-note" maxlength="180" placeholder="Một dòng ghi chú"><input name="memory-date" type="date" value="${today()}" required><button class="primary-button" type="submit">Lưu kỷ niệm</button></form>${features.memories.length ? `<div class="memory-list">${features.memories.map((memory) => `<article><small>${formatCalendarDate(calendarDate(memory.date))}</small><h3>${escapeHtml(memory.title)}</h3><p>${escapeHtml(memory.note)}</p></article>`).join("")}</div>` : "<p>Chưa có kỷ niệm nào. Hãy lưu lại khoảnh khắc đầu tiên.</p>"}</section><section class="history-card"><div class="section-heading"><h2>50 điều nên làm khi yêu</h2><span class="task-count">${features.checklist.filter((item) => item.done).length}/${features.checklist.length}</span></div><ul class="checklist">${features.checklist.map((item) => `<li><button type="button" data-checklist="${item.id}" class="${item.done ? "done" : ""}" aria-label="Đánh dấu ${item.done ? "chưa hoàn thành" : "đã hoàn thành"}">${item.done ? "Đã xong" : "Hoàn thành"}</button><span class="${item.done ? "done" : ""}">${escapeHtml(item.title)}</span></li>`).join("")}</ul></section></section>`; }
function insights(context: RenderContext): string { const prediction = predictCycle({ periods: context.periods, asOfDate: today() }); return `<section class="content-page"><p class="eyebrow">HIỂU HƠN MỖI NGÀY</p><h1>Nhịp của bạn</h1><p class="page-lead">Một vài điểm chạm nhẹ nhàng, không thay thế tư vấn y tế.</p><section class="insight-feature"><span class="insight-mark">●</span><small>DỰ ĐOÁN KỲ TIẾP THEO</small><h2>${prediction.expectedDate ? formatCalendarDate(prediction.expectedDate) : "Chưa đủ dữ liệu"}</h2><p>Ghi nhận đều đặn giúp dự đoán ngày càng phù hợp hơn.</p></section><div class="insight-grid"><section><small>Chu kỳ điển hình</small><strong>${prediction.cycleLength.expected ? `${prediction.cycleLength.expected} ngày` : "Chưa đủ dữ liệu"}</strong></section><section><small>Lần ghi nhận</small><strong>${context.periods.length}</strong></section></div></section>`; }
function settings(context: RenderContext, membership: CoupleMembership): string { const state = notificationState(); const theme = currentTheme(); const avatarKey = context.authSession.status === "authenticated" ? `nhip-doi:avatar:${context.authSession.user.uid}` : ""; let avatar = ""; try { avatar = avatarKey ? localStorage.getItem(avatarKey) ?? "" : ""; } catch { /* ignore */ } return `<section class="content-page"><p class="eyebrow">KHÔNG GIAN CỦA BẠN</p><h1>Cá nhân & riêng tư</h1><section class="settings-card"><span class="profile-avatar">${avatar ? `<img src="${escapeHtml(avatar)}" alt="Ảnh đại diện của bạn">` : escapeHtml(membership.profile.name.slice(0, 1))}</span><div><strong>${escapeHtml(membership.profile.name)}</strong><p>Không gian chỉ dành cho hai bạn</p><label class="avatar-upload">Đổi ảnh đại diện<input id="avatar-input" type="file" accept="image/jpeg,image/png,image/webp"></label></div></section><p id="avatar-status" class="form-status"></p><section class="settings-group"><h2>Thông báo</h2><button id="notification-button" class="settings-row" type="button"><span>Thông báo</span><div><strong>Nhắc ngày quan trọng</strong><small>${state === "granted" ? "Đã bật trên thiết bị này" : "Bật để nhận lời nhắc đúng lúc"}</small></div><b>${state === "granted" ? "Đã bật" : "Bật"}</b></button><p id="notification-status" class="form-status"></p><button id="notification-check" class="settings-row" type="button"><span>Kiểm tra</span><div><strong>Kiểm tra thông báo</strong><small>Quyền trình duyệt và Service Worker</small></div></button><p id="notification-check-status" class="form-status"></p></section><section class="settings-group"><h2>Tùy chỉnh không gian</h2><label class="field">Chủ đề màu<select id="theme-select">${(["cream", "peach", "lavender", "sunset", "night", "minimal"] as ThemeName[]).map((name) => `<option value="${name}" ${name === theme ? "selected" : ""}>${name === "cream" ? "Kem ấm" : name === "peach" ? "Hồng đào" : name === "lavender" ? "Lavender" : name === "sunset" ? "Hoàng hôn" : name === "night" ? "Xanh đêm" : "Trắng tối giản"}</option>`).join("")}</select></label><p class="settings-note">Chủ đề được lưu trên thiết bị và vẫn hoạt động khi offline.</p></section><section class="settings-group"><h2>Dữ liệu</h2><div class="settings-row"><span>Riêng tư</span><div><strong>Dữ liệu của hai bạn</strong><small>Check-in riêng tư, sự kiện và việc chung được giới hạn theo Firebase Rules.</small></div></div><div class="settings-row"><span>Đồng bộ</span><div><strong>Trạng thái kết nối</strong><small>${syncText(context.syncState)}</small></div></div></section><button id="logout-button" class="secondary-button logout-button" type="button">Đăng xuất</button></section>`; }
function eventForm(): string { const holidays = suggestedHolidays(today()); return `<div id="sheet-backdrop" class="sheet-backdrop"><section class="event-sheet"><button id="close-sheet" class="sheet-close" type="button">×</button><span class="sheet-pill"></span><p class="eyebrow">NGÀY CỦA HAI BẠN</p><h2>Thêm một điều đáng nhớ</h2><form id="event-form">${field("event-title", "Tên sự kiện", "text", "Ví dụ: Kỷ niệm yêu nhau")}<div class="holiday-suggestions"><small>Gợi ý ngày lễ</small><div>${holidays.map((holiday) => `<button data-holiday-title="${escapeHtml(holiday.title)}" data-holiday-date="${holiday.date}" type="button">${escapeHtml(holiday.title)}</button>`).join("")}</div></div><div class="event-form-grid"><label class="field">Ngày diễn ra<input id="event-date" name="event-date" type="date" value="${today()}" required></label><label class="field">Loại ngày<select name="kind"><option value="anniversary">Kỷ niệm</option><option value="birthday">Sinh nhật</option><option value="date">Hẹn hò</option><option value="holiday">Ngày lễ</option><option value="custom">Tùy chỉnh</option></select></label></div><fieldset><legend>Nhắc trước</legend><label><input type="checkbox" name="reminder" value="7" checked> 7 ngày</label><label><input type="checkbox" name="reminder" value="3" checked> 3 ngày</label><label><input type="checkbox" name="reminder" value="1" checked> 1 ngày</label><label><input type="checkbox" name="reminder" value="0"> Đúng ngày</label></fieldset><p class="form-status"></p><button class="primary-button" type="submit">Lưu ngày quan trọng →</button></form></section></div>`; }

function bindCommon(root: HTMLElement, context: RenderContext, membership: CoupleMembership): void {
  root.querySelectorAll<HTMLButtonElement>("[data-open-event]").forEach((button) => button.addEventListener("click", () => { composerOpen = true; context.rerender(); }));
  root.querySelector<HTMLFormElement>("#love-date-form")?.addEventListener("submit", (event) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const value = String(new FormData(form).get("love-date") ?? "");
    const startDate = loveDateFromInput(value);
    if (!startDate || startDate > today()) { setFormStatus(form, "Hãy chọn ngày bắt đầu hợp lệ, không ở tương lai."); return; }
    const button = form.querySelector<HTMLButtonElement>("button[type=submit]");
    if (button) button.disabled = true;
    void context.updateStartDate(startDate).then(context.rerender).catch((error: unknown) => {
      if (button) button.disabled = false;
      setFormStatus(form, error instanceof Error ? error.message : "Không thể lưu ngày bắt đầu.");
    });
  });
  root.querySelector<HTMLButtonElement>("[data-copy-love]")?.addEventListener("click", () => {
    const text = root.querySelector<HTMLElement>(".love-count")?.textContent ? `Bọn mình đã bên nhau ${root.querySelector<HTMLElement>(".love-count")?.textContent} ngày cùng Nhịp Đôi.` : "Hành trình của Nhịp Đôi";
    if (!navigator.clipboard) return;
    void navigator.clipboard.writeText(text).then(() => window.alert("Đã sao chép lời nhắn để chia sẻ."));
  });
  root.querySelector<HTMLButtonElement>("#close-sheet")?.addEventListener("click", () => { composerOpen = false; context.rerender(); });
  root.querySelector<HTMLButtonElement>("#logout-button")?.addEventListener("click", () => { void context.auth.logout().then(() => context.navigate("/login")); });
  root.querySelector<HTMLSelectElement>("#theme-select")?.addEventListener("change", (event) => { applyTheme((event.currentTarget as HTMLSelectElement).value as ThemeName); });
  root.querySelector<HTMLInputElement>("#avatar-input")?.addEventListener("change", async (event) => { const file = (event.currentTarget as HTMLInputElement).files?.[0]; if (!file || context.authSession.status !== "authenticated") return; const status = root.querySelector<HTMLElement>("#avatar-status"); try { const url = await uploadAvatar(userId(context), file); localStorage.setItem(`nhip-doi:avatar:${userId(context)}`, url); if (status) status.textContent = "Đã cập nhật ảnh đại diện."; context.rerender(); } catch (error) { if (status) status.textContent = error instanceof Error ? error.message : "Không thể cập nhật ảnh."; } });
  root.querySelector<HTMLButtonElement>("#notification-check")?.addEventListener("click", async () => { const target = root.querySelector<HTMLElement>("#notification-check-status"); const registration = await navigator.serviceWorker?.getRegistration(); if (target) target.textContent = `Quyền: ${notificationState()} · Service Worker: ${registration ? "đang hoạt động" : "chưa hoạt động"} · FCM: ${context.firebaseConfigured ? "đã cấu hình" : "offline"}.`; });
  root.querySelector<HTMLButtonElement>("#notification-button")?.addEventListener("click", () => { void askForNotificationPermission().then(async (permission) => { if (permission !== "granted") { context.rerender(); return; } if (!context.firebaseConfigured) { setText(root, "#notification-status", "Đã bật nhắc khi ứng dụng đang mở. Kết nối Firebase để nhận push khi app đóng."); return; } const result = await enableFirebasePush(membership.coupleId, userId(context)); if (result === "missing-vapid") setText(root, "#notification-status", "Thiếu VAPID key. Hãy thêm VITE_FIREBASE_VAPID_KEY vào cấu hình."); else if (result === "unsupported") setText(root, "#notification-status", "Trình duyệt này chưa hỗ trợ thông báo đẩy."); else context.rerender(); }).catch(() => setText(root, "#notification-status", "Không thể bật thông báo trên thiết bị này.")); });
  root.querySelectorAll<HTMLButtonElement>("[data-mood]").forEach((button) => button.addEventListener("click", () => {
    const mood = button.dataset.mood as Mood | undefined;
    if (!mood) return;
    void context.dailyService.saveCheckin(userId(context), membership.coupleId, today(), mood).catch(() => setText(root, ".privacy-note", "Chưa thể lưu check-in. Bạn hãy thử lại nhé."));
  }));
  root.querySelector<HTMLFormElement>("#memory-form")?.addEventListener("submit", (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); const title = String(data.get("memory-title") ?? "").trim(); const note = String(data.get("memory-note") ?? ""); const date = String(data.get("memory-date") ?? today()); if (title.length < 2) return; void context.featureService.addMemory(membership.coupleId, userId(context), title, note, date).then(context.rerender).catch(() => setText(root, ".memory-form", "Không thể lưu kỷ niệm.")); });
  root.querySelectorAll<HTMLButtonElement>("[data-checklist]").forEach((button) => button.addEventListener("click", () => { const item = context.featureService.list(membership.coupleId).checklist.find((entry) => entry.id === button.dataset.checklist); if (item) void context.featureService.toggleChecklist(membership.coupleId, userId(context), item).then(context.rerender).catch(() => undefined); }));
  root.querySelector<HTMLFormElement>("#task-form")?.addEventListener("submit", (event) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const title = String(new FormData(form).get("task-title") ?? "");
    void context.dailyService.createTask(membership.coupleId, userId(context), title).then(() => form.reset()).catch((error: unknown) => window.alert(error instanceof Error ? error.message : "Không thể thêm việc chung."));
  });
  root.querySelectorAll<HTMLButtonElement>("[data-toggle-task]").forEach((button) => button.addEventListener("click", () => {
    const task = context.sharedTasks.find((item) => item.id === button.dataset.toggleTask);
    if (task) void context.dailyService.toggleTask(membership.coupleId, task, userId(context)).catch(() => window.alert("Không thể cập nhật việc chung."));
  }));
  root.querySelectorAll<HTMLButtonElement>("[data-holiday-title]").forEach((button) => button.addEventListener("click", () => {
    const form = root.querySelector<HTMLFormElement>("#event-form");
    const title = form?.querySelector<HTMLInputElement>("#event-title");
    const date = form?.querySelector<HTMLInputElement>("#event-date");
    const kind = form?.querySelector<HTMLSelectElement>("select[name=kind]");
    if (title) title.value = button.dataset.holidayTitle ?? "";
    if (date) date.value = button.dataset.holidayDate ?? "";
    if (kind) kind.value = "holiday";
  }));
  root.querySelectorAll<HTMLButtonElement>("[data-remove-event]").forEach((button) => button.addEventListener("click", () => { if (!window.confirm("Xóa ngày quan trọng này?")) return; void context.eventService.remove(membership.coupleId, button.dataset.removeEvent ?? "").catch(() => undefined); }));
  root.querySelector<HTMLFormElement>("#event-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const data = new FormData(form); let date: CalendarDate; try { date = calendarDate(String(data.get("event-date"))); } catch { setFormStatus(form, "Hãy chọn ngày hợp lệ."); return; } void context.eventService.create(membership.coupleId, userId(context), { title: String(data.get("event-title") ?? ""), date, kind: String(data.get("kind")) as CoupleEventKind, reminderDays: data.getAll("reminder").map(Number) }).then(() => { composerOpen = false; context.rerender(); }).catch((error: unknown) => setFormStatus(form, error instanceof Error ? error.message : "Không thể lưu sự kiện.")); });
}
function renderOnboarding(root: HTMLElement, context: RenderContext): void {
  const query = queryFromHash(window.location.hash);
  root.innerHTML = shell(`<main class="page onboarding-page"><p class="eyebrow">BẮT ĐẦU CÙNG NHAU</p><h1>Tạo không gian của hai bạn</h1><p class="page-lead">Mỗi không gian chỉ dành cho đúng hai người.</p><section class="auth-card flow-card"><h2>Tạo không gian</h2><form id="couple-form">${field("name", "Tên không gian", "text", "Ví dụ: Minh & An")}${submit("Tạo và mời người ấy")}</form></section></main>`);
  root.querySelector<HTMLFormElement>("#couple-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; void context.couples.createCouple(userId(context), String(new FormData(form).get("name") ?? "")).then((result) => { context.setMembership(result.membership, result.invite); context.navigate("/invite"); }).catch((error: unknown) => setFormStatus(form, error instanceof Error ? error.message : "Không thể tạo không gian.")); });
  if (query.get("couple")) void query;
}
function setText(root: HTMLElement, selector: string, message: string): void { const target = root.querySelector<HTMLElement>(selector); if (target) target.textContent = message; }
function renderInvite(root: HTMLElement, context: RenderContext): void {
  const invite = context.invite;
  const url = invite ? `${window.location.origin}${window.location.pathname}#/onboarding?couple=${encodeURIComponent(invite.coupleId)}&invite=${encodeURIComponent(invite.code)}` : "";
  root.innerHTML = shell(`<main class="page"><section class="notice-card invite-card"><span class="hero-orb">♡</span><p class="eyebrow">MỜI NGƯỜI ẤY</p><h1>Chia sẻ không gian này</h1><p>Gửi liên kết riêng tư bên dưới cho người bạn muốn đồng hành.</p>${invite ? `<div class="share-row"><input id="invite-link" readonly value="${escapeHtml(url)}"><button id="copy-invite" class="secondary-button" type="button">Sao chép</button></div>` : "<p>Đang tạo lời mời…</p>"}<a class="primary-link" data-route href="#/home">Đến trang hôm nay →</a></section></main>`);
  root.querySelector<HTMLButtonElement>("#copy-invite")?.addEventListener("click", () => { void navigator.clipboard.writeText(url); });
}
