import { get, onValue, push, ref, serverTimestamp, set, update, type Unsubscribe } from "firebase/database";
import { getFirebaseDatabase } from "../firebase/database";

export interface Memory { id: string; title: string; note: string; date: string; createdAt: number; createdBy: string; }
export interface ChecklistItem { id: string; title: string; done: boolean; createdAt: number; createdBy: string; completedAt?: number; completedBy?: string; }
export interface CoupleFeatures { memories: Memory[]; checklist: ChecklistItem[]; }
const defaults = ["Nấu một bữa ăn cùng nhau", "Đi xem bình minh", "Viết thư tay cho nhau", "Cùng học một điều mới", "Tạo một album ảnh chung"];
const key = (coupleId: string) => `nhip-doi:features:${coupleId}`;
const empty = (): CoupleFeatures => ({ memories: [], checklist: defaults.map((title, index) => ({ id: `default-${index}`, title, done: false, createdAt: 0, createdBy: "system" })) });
function parse(value: unknown): CoupleFeatures { if (!value || typeof value !== "object") return empty(); const raw = value as { memories?: Record<string, Record<string, unknown>>; checklist?: Record<string, Record<string, unknown>> }; const memories = Object.entries(raw.memories ?? {}).flatMap(([id, item]) => typeof item.title === "string" && typeof item.note === "string" && typeof item.date === "string" && typeof item.createdAt === "number" && typeof item.createdBy === "string" ? [{ id, title: item.title, note: item.note, date: item.date, createdAt: item.createdAt, createdBy: item.createdBy }] : []).sort((a, b) => b.date.localeCompare(a.date)); const checklist = Object.entries(raw.checklist ?? {}).flatMap(([id, item]) => typeof item.title === "string" && typeof item.done === "boolean" && typeof item.createdAt === "number" && typeof item.createdBy === "string" ? [{ id, title: item.title, done: item.done, createdAt: item.createdAt, createdBy: item.createdBy, ...(typeof item.completedAt === "number" ? { completedAt: item.completedAt } : {}), ...(typeof item.completedBy === "string" ? { completedBy: item.completedBy } : {}) }] : []).sort((a, b) => Number(a.done) - Number(b.done) || a.title.localeCompare(b.title)); return { memories, checklist: checklist.length ? checklist : empty().checklist }; }
export class CoupleFeatureService {
  constructor(private readonly remoteEnabled: boolean) {}
  private read(coupleId: string): CoupleFeatures { try { return parse(JSON.parse(localStorage.getItem(key(coupleId)) ?? "null")); } catch { return empty(); } }
  private write(coupleId: string, value: CoupleFeatures): void { try { localStorage.setItem(key(coupleId), JSON.stringify(value)); } catch { /* local cache is best effort */ } }
  list(coupleId: string): CoupleFeatures { return this.read(coupleId); }
  subscribe(coupleId: string, callback: (features: CoupleFeatures) => void): Unsubscribe { if (!this.remoteEnabled) { callback(this.read(coupleId)); return () => undefined; } return onValue(ref(getFirebaseDatabase(), `couples/${coupleId}/features`), (snapshot) => { const value = parse(snapshot.val()); this.write(coupleId, value); callback(value); }); }
  async migrate(coupleId: string, uid: string): Promise<void> { if (!this.remoteEnabled) return; const remote = await get(ref(getFirebaseDatabase(), `couples/${coupleId}/features`)); if (remote.exists()) return; const cached = this.read(coupleId); const checklist = cached.checklist.length ? cached.checklist : empty().checklist; await set(ref(getFirebaseDatabase(), `couples/${coupleId}/features`), { checklist: Object.fromEntries(checklist.map((item) => [item.id, { title: item.title, done: item.done, createdAt: item.createdAt || serverTimestamp(), createdBy: item.createdBy === "system" ? uid : item.createdBy, ...(item.done ? { completedAt: item.completedAt || serverTimestamp(), completedBy: item.completedBy || uid } : {}) }])), memories: Object.fromEntries(cached.memories.map((item) => [item.id, { title: item.title, note: item.note, date: item.date, createdAt: item.createdAt || serverTimestamp(), createdBy: item.createdBy || uid }])) }); }
  async addMemory(coupleId: string, uid: string, titleRaw: string, noteRaw: string, date: string): Promise<void> { const title = titleRaw.trim(); const note = noteRaw.trim(); if (title.length < 2 || title.length > 80 || note.length > 500 || !/^\d{4}-\d{2}-\d{2}$/u.test(date)) throw new Error("Kỷ niệm chưa hợp lệ."); if (!this.remoteEnabled) { const value = this.read(coupleId); value.memories.unshift({ id: crypto.randomUUID(), title, note, date, createdAt: Date.now(), createdBy: uid }); this.write(coupleId, value); return; } const target = push(ref(getFirebaseDatabase(), `couples/${coupleId}/features/memories`)); await set(target, { title, note, date, createdAt: serverTimestamp(), createdBy: uid }); }
  async toggleChecklist(coupleId: string, uid: string, item: ChecklistItem): Promise<void> { const done = !item.done; if (!this.remoteEnabled) { const value = this.read(coupleId); const target = value.checklist.find((entry) => entry.id === item.id); if (target) Object.assign(target, { done, ...(done ? { completedAt: Date.now(), completedBy: uid } : { completedAt: undefined, completedBy: undefined }) }); this.write(coupleId, value); return; } await update(ref(getFirebaseDatabase(), `couples/${coupleId}/features/checklist/${item.id}`), done ? { done: true, completedAt: serverTimestamp(), completedBy: uid } : { done: false, completedAt: null, completedBy: null }); }
}
